# version: 2.1
# setup: true
# orbs:
#   continuation: circleci/continuation@0.1.2
#   conditional-jobs: doth/conditional-jobs@dev:alpha
#   config-splitting: circle-makotom-orbs/config-splitting@0.0.3

# jobs:
#   combine-and-optional:
#     docker:
#         - image: cimg/python:3.8
#     resource_class: small
#     steps:
#         - checkout
#         - config-splitting/prepare
#         - config-splitting/combine-configs:
#             config-list-file: .circleci/.circleci-config-dependencies
#             output: /tmp/continuation-config.yml
#             shared-config-file: .circleci/continue-shared.yml
#         - conditional-jobs/workflow-job-patching:
#             circleci-config-path: /tmp/continuation-config.yml
#             output-config-path: /tmp/continuation-config.yml
#             jobs-to-transform: "failing-job"
#         - continuation/continue:
#             configuration_path: /tmp/continuation-config.yml

# workflows:
#   setup:
#     jobs:
#       - combine-and-optional


jobs:
  echo:
    docker:
    - image: cimg/base:2023.06
    parameters:
      message:
        type: string
    steps:
    - run: echo << parameters.message >>
  failing-job:
    docker:
    - image: cimg/base:2023.06
    steps:
    - run: exit 1
  succeeding-job:
    docker:
    - image: cimg/base:2023.06
    steps:
    - run: exit 0
version: 2.1
workflows:
  echo-hello-world:
    jobs:
    - echo:
        message: Hello!
  run-succeed-and-fail:
    jobs:
    - succeeding-job
    - failing-job:
      context: global
      type: approval
  version: 2
