version: 2.1
setup: true
orbs:
  continuation: circleci/continuation@0.1.2
  conditional-jobs: doth/conditional-jobs@dev:241ff7518d7e0e532a74992fa498eddd684f9fe0
  config-splitting: circle-makotom-orbs/config-splitting@0.0.3

jobs:
  combine-and-optional:
    docker:
        - image: cimg/python:3.8
    resource_class: small
    steps:
        - checkout
        - config-splitting/prepare
        - config-splitting/combine-configs:
            config-list-file: .circleci/.circleci-config-dependencies
            output: /tmp/continuation-config.yml
            shared-config-file: .circleci/continue-shared.yml
        - conditional-jobs/workflow-job-patching:
            circleci-config-path: /tmp/continuation-config.yml
            output-config-path: /tmp/continuation-config.yml
            jobs-to-transform-config-path: .circleci/jobs-to-transform.yml
        - continuation/continue:
            configuration_path: /tmp/continuation-config.yml

workflows:
  setup:
    jobs:
      - combine-and-optional
