changed-files:
    # The revision to compare the current one against for the purpose of determining changed files.
    base-revision: main
    # The regex to apply on the changed files path
    # Syntax is https://docs.python.org/fr/3/library/re.html#regular-expression-syntax
    regex: ^.circleci/.yml$
